import Category from "./category";
import Designer from "./designer";
import Entity from "./entity";
import Mechanic from "./mechanic";
import MultipleSizeImage from "./multiple-size-image";
import Publisher from "./publisher";

export default interface BoardgameatlasBoardGame extends Entity {
  active: boolean;
  amazon_rank: number;
  artists: string[];
  average_learning_complexity: number;
  average_strategy_complexity: number;
  average_user_rating: number;
  bgg_id: number;
  comment_count: number;
  commentary: string;
  description: string;
  description_preview: string;
  discount: string;
  handle: string;
  image_url: string;
  images: MultipleSizeImage;
  is_historical_low: boolean;
  links: number;
  listing_clicks: number;
  lists: number;
  matches_specs: any;
  max_players: number;
  max_playtime: number;
  mentions: number;
  min_age: number;
  min_players: number;
  min_playtime: number;
  msrp: number;
  msrp_text: number;
  msrps: number;
  name: string;
  names: string[],
  num_user_complexity_vote: number;
  num_user_ratings: number;
  official_url: string;
  plays: number;
  price: string;
  price_au: string;
  price_ca: string;
  price_text: string;
  price_uk: string;
  publisher: string;
  rank: number;
  rules_url: string;
  size_depth: number;
  size_height: number;
  size_units: string;
  tags: string[];
  thumb_url: string;
  trending_rank: number;
  visits: number;
  weight_amount: number;
  weight_units: string;
  year_published: number;
  
  categories: Category[];
  designers: Designer[];
  developers: any[];
  historical_low_prices: any[];
  mechanics: Mechanic[];
  primary_designer: Designer;
  primary_publisher: Publisher;
  publishers: Publisher[];
  specs: any[];
};
